// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protofiles/payment_gateway.proto

package payment_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionState_State int32

const (
	TransactionState_PENDING   TransactionState_State = 0
	TransactionState_COMMITTED TransactionState_State = 1
	TransactionState_ABORTED   TransactionState_State = 2
	TransactionState_TIMEOUT   TransactionState_State = 3
)

// Enum value maps for TransactionState_State.
var (
	TransactionState_State_name = map[int32]string{
		0: "PENDING",
		1: "COMMITTED",
		2: "ABORTED",
		3: "TIMEOUT",
	}
	TransactionState_State_value = map[string]int32{
		"PENDING":   0,
		"COMMITTED": 1,
		"ABORTED":   2,
		"TIMEOUT":   3,
	}
)

func (x TransactionState_State) Enum() *TransactionState_State {
	p := new(TransactionState_State)
	*p = x
	return p
}

func (x TransactionState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_payment_gateway_proto_enumTypes[0].Descriptor()
}

func (TransactionState_State) Type() protoreflect.EnumType {
	return &file_protofiles_payment_gateway_proto_enumTypes[0]
}

func (x TransactionState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState_State.Descriptor instead.
func (TransactionState_State) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{1, 0}
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type TransactionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  TransactionState_State `protobuf:"varint,1,opt,name=current_state,json=currentState,proto3,enum=payment_gateway.TransactionState_State" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionState) Reset() {
	*x = TransactionState{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionState) ProtoMessage() {}

func (x *TransactionState) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionState.ProtoReflect.Descriptor instead.
func (*TransactionState) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionState) GetCurrentState() TransactionState_State {
	if x != nil {
		return x.CurrentState
	}
	return TransactionState_PENDING
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{4}
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PaymentRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *PaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_protofiles_payment_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_payment_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_payment_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protofiles_payment_gateway_proto protoreflect.FileDescriptor

const file_protofiles_payment_gateway_proto_rawDesc = "" +
	"\n" +
	" protofiles/payment_gateway.proto\x12\x0fpayment_gateway\";\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x9f\x01\n" +
	"\x10TransactionState\x12L\n" +
	"\rcurrent_state\x18\x01 \x01(\x0e2'.payment_gateway.TransactionState.StateR\fcurrentState\"=\n" +
	"\x05State\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\v\n" +
	"\aABORTED\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x10\n" +
	"\x0eBalanceRequest\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\"\x83\x01\n" +
	"\x0ePaymentRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\"E\n" +
	"\x0fPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xde\x02\n" +
	"\x0ePaymentGateway\x12F\n" +
	"\x05Login\x12\x1d.payment_gateway.LoginRequest\x1a\x1e.payment_gateway.LoginResponse\x12P\n" +
	"\vViewBalance\x12\x1f.payment_gateway.BalanceRequest\x1a .payment_gateway.BalanceResponse\x12S\n" +
	"\x0eProcessPayment\x12\x1f.payment_gateway.PaymentRequest\x1a .payment_gateway.PaymentResponse\x12]\n" +
	"\x13GetTransactionState\x12#.payment_gateway.TransactionRequest\x1a!.payment_gateway.TransactionStateB\x1eZ\x1c./protofiles/payment_gatewayb\x06proto3"

var (
	file_protofiles_payment_gateway_proto_rawDescOnce sync.Once
	file_protofiles_payment_gateway_proto_rawDescData []byte
)

func file_protofiles_payment_gateway_proto_rawDescGZIP() []byte {
	file_protofiles_payment_gateway_proto_rawDescOnce.Do(func() {
		file_protofiles_payment_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protofiles_payment_gateway_proto_rawDesc), len(file_protofiles_payment_gateway_proto_rawDesc)))
	})
	return file_protofiles_payment_gateway_proto_rawDescData
}

var file_protofiles_payment_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofiles_payment_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protofiles_payment_gateway_proto_goTypes = []any{
	(TransactionState_State)(0), // 0: payment_gateway.TransactionState.State
	(*TransactionRequest)(nil),  // 1: payment_gateway.TransactionRequest
	(*TransactionState)(nil),    // 2: payment_gateway.TransactionState
	(*LoginRequest)(nil),        // 3: payment_gateway.LoginRequest
	(*LoginResponse)(nil),       // 4: payment_gateway.LoginResponse
	(*BalanceRequest)(nil),      // 5: payment_gateway.BalanceRequest
	(*BalanceResponse)(nil),     // 6: payment_gateway.BalanceResponse
	(*PaymentRequest)(nil),      // 7: payment_gateway.PaymentRequest
	(*PaymentResponse)(nil),     // 8: payment_gateway.PaymentResponse
}
var file_protofiles_payment_gateway_proto_depIdxs = []int32{
	0, // 0: payment_gateway.TransactionState.current_state:type_name -> payment_gateway.TransactionState.State
	3, // 1: payment_gateway.PaymentGateway.Login:input_type -> payment_gateway.LoginRequest
	5, // 2: payment_gateway.PaymentGateway.ViewBalance:input_type -> payment_gateway.BalanceRequest
	7, // 3: payment_gateway.PaymentGateway.ProcessPayment:input_type -> payment_gateway.PaymentRequest
	1, // 4: payment_gateway.PaymentGateway.GetTransactionState:input_type -> payment_gateway.TransactionRequest
	4, // 5: payment_gateway.PaymentGateway.Login:output_type -> payment_gateway.LoginResponse
	6, // 6: payment_gateway.PaymentGateway.ViewBalance:output_type -> payment_gateway.BalanceResponse
	8, // 7: payment_gateway.PaymentGateway.ProcessPayment:output_type -> payment_gateway.PaymentResponse
	2, // 8: payment_gateway.PaymentGateway.GetTransactionState:output_type -> payment_gateway.TransactionState
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protofiles_payment_gateway_proto_init() }
func file_protofiles_payment_gateway_proto_init() {
	if File_protofiles_payment_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protofiles_payment_gateway_proto_rawDesc), len(file_protofiles_payment_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_payment_gateway_proto_goTypes,
		DependencyIndexes: file_protofiles_payment_gateway_proto_depIdxs,
		EnumInfos:         file_protofiles_payment_gateway_proto_enumTypes,
		MessageInfos:      file_protofiles_payment_gateway_proto_msgTypes,
	}.Build()
	File_protofiles_payment_gateway_proto = out.File
	file_protofiles_payment_gateway_proto_goTypes = nil
	file_protofiles_payment_gateway_proto_depIdxs = nil
}
